// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  pin: __t.string(),
  host: __t.identity(),
  title: __t.string(),
  kahootId: __t.string().name("kahoot_id"),
  phase: __t.string(),
  questionIndex: __t.u32().name("question_index"),
  questionCount: __t.u32().name("question_count"),
  showQuestionOnPlayer: __t.bool().name("show_question_on_player"),
  phaseStartedAt: __t.timestamp().name("phase_started_at"),
  phaseDurationMs: __t.u32().name("phase_duration_ms"),
  createdAt: __t.timestamp().name("created_at"),
});
