// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  gameId: __t.u64().name("game_id"),
  nickname: __t.string(),
  score: __t.u32(),
  streak: __t.u32(),
  correctCount: __t.u32().name("correct_count"),
  connected: __t.bool(),
  answered: __t.bool(),
});
