// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.u64().primaryKey().name("game_id"),
  index: __t.u32(),
  qtype: __t.string(),
  prompt: __t.string(),
  imageUrl: __t.string().name("image_url"),
  timeLimitMs: __t.u32().name("time_limit_ms"),
  pointsMultiplier: __t.u32().name("points_multiplier"),
  option0: __t.string().name("option_0"),
  option1: __t.string().name("option_1"),
  option2: __t.string().name("option_2"),
  option3: __t.string().name("option_3"),
  optionCount: __t.u32().name("option_count"),
  sliderMin: __t.i32().name("slider_min"),
  sliderMax: __t.i32().name("slider_max"),
});
