// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.u64().primaryKey().name("game_id"),
  correctMask: __t.u32().name("correct_mask"),
  typeAnswer: __t.string().name("type_answer"),
  sliderCorrect: __t.i32().name("slider_correct"),
  count0: __t.u32().name("count_0"),
  count1: __t.u32().name("count_1"),
  count2: __t.u32().name("count_2"),
  count3: __t.u32().name("count_3"),
  typedCorrect: __t.u32().name("typed_correct"),
});
