// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Answer = __t.object("Answer", {
  id: __t.u64(),
  gameId: __t.u64(),
  player: __t.identity(),
  questionIndex: __t.u32(),
  choiceMask: __t.u32(),
  typed: __t.string(),
  sliderValue: __t.i32(),
  isCorrect: __t.bool(),
  points: __t.u32(),
  elapsedMs: __t.u32(),
});
export type Answer = __Infer<typeof Answer>;

export const Game = __t.object("Game", {
  id: __t.u64(),
  pin: __t.string(),
  host: __t.identity(),
  title: __t.string(),
  kahootId: __t.string(),
  phase: __t.string(),
  questionIndex: __t.u32(),
  questionCount: __t.u32(),
  showQuestionOnPlayer: __t.bool(),
  phaseStartedAt: __t.timestamp(),
  phaseDurationMs: __t.u32(),
  createdAt: __t.timestamp(),
});
export type Game = __Infer<typeof Game>;

export const PhaseTimer = __t.object("PhaseTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
  expectedPhase: __t.string(),
  expectedQuestion: __t.u32(),
});
export type PhaseTimer = __Infer<typeof PhaseTimer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  gameId: __t.u64(),
  nickname: __t.string(),
  score: __t.u32(),
  streak: __t.u32(),
  correctCount: __t.u32(),
  connected: __t.bool(),
  answered: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const QuestionPublic = __t.object("QuestionPublic", {
  gameId: __t.u64(),
  index: __t.u32(),
  qtype: __t.string(),
  prompt: __t.string(),
  imageUrl: __t.string(),
  timeLimitMs: __t.u32(),
  pointsMultiplier: __t.u32(),
  option0: __t.string(),
  option1: __t.string(),
  option2: __t.string(),
  option3: __t.string(),
  optionCount: __t.u32(),
  sliderMin: __t.i32(),
  sliderMax: __t.i32(),
});
export type QuestionPublic = __Infer<typeof QuestionPublic>;

export const QuizOption = __t.object("QuizOption", {
  text: __t.string(),
  correct: __t.bool(),
});
export type QuizOption = __Infer<typeof QuizOption>;

export const QuizQuestion = __t.object("QuizQuestion", {
  qtype: __t.string(),
  prompt: __t.string(),
  imageUrl: __t.string(),
  timeLimitMs: __t.u32(),
  pointsMultiplier: __t.u32(),
  get options() {
    return __t.array(QuizOption);
  },
  typeAnswers: __t.array(__t.string()),
  sliderMin: __t.i32(),
  sliderMax: __t.i32(),
  sliderCorrect: __t.i32(),
  sliderTolerance: __t.i32(),
});
export type QuizQuestion = __Infer<typeof QuizQuestion>;

export const QuizSecret = __t.object("QuizSecret", {
  gameId: __t.u64(),
  get questions() {
    return __t.array(QuizQuestion);
  },
});
export type QuizSecret = __Infer<typeof QuizSecret>;

export const Result = __t.object("Result", {
  id: __t.u64(),
  gameId: __t.u64(),
  player: __t.identity(),
  questionIndex: __t.u32(),
  isCorrect: __t.bool(),
  points: __t.u32(),
});
export type Result = __Infer<typeof Result>;

export const Reveal = __t.object("Reveal", {
  gameId: __t.u64(),
  correctMask: __t.u32(),
  typeAnswer: __t.string(),
  sliderCorrect: __t.i32(),
  count0: __t.u32(),
  count1: __t.u32(),
  count2: __t.u32(),
  count3: __t.u32(),
  typedCorrect: __t.u32(),
});
export type Reveal = __Infer<typeof Reveal>;

export const Tally = __t.object("Tally", {
  gameId: __t.u64(),
  answeredCount: __t.u32(),
  playerCount: __t.u32(),
});
export type Tally = __Infer<typeof Tally>;

