// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceReducer from "../advance_reducer";
import FinishGameReducer from "../finish_game_reducer";
import HostGameReducer from "../host_game_reducer";
import JoinGameReducer from "../join_game_reducer";
import KickPlayerReducer from "../kick_player_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitAnswerReducer from "../submit_answer_reducer";

export type AdvanceParams = __Infer<typeof AdvanceReducer>;
export type FinishGameParams = __Infer<typeof FinishGameReducer>;
export type HostGameParams = __Infer<typeof HostGameReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type KickPlayerParams = __Infer<typeof KickPlayerReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitAnswerParams = __Infer<typeof SubmitAnswerReducer>;

