server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  gzip on;

  location /r/ {
    proxy_pass http://rsshub:1200/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 60s;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
