FROM lscr.io/linuxserver/grav:latest
COPY pages /app/www/public/user/pages
COPY pages /config/www/grav/user/pages
COPY plugins/umami /app/www/public/user/plugins/umami
COPY plugins/umami /config/www/grav/user/plugins/umami
COPY config/plugins/umami.yaml /app/www/public/user/config/plugins/umami.yaml
COPY config/plugins/umami.yaml /config/www/grav/user/config/plugins/umami.yaml
